name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install sphinx sphinx-book-theme furo ghp-import

      - name: Build HTML
        run: |
          sphinx-build docs docs/_build/html

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # your personal access token
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          ghp-import -n -p -f docs/_build/html